### ISSUE TITLE
LiteRT: Exchange of the model file crashes inferencing...

### ISSUE THREAD

**Issue by ludgerh** [ludgerh/cam-ai#79]
When exchanging model file when running (for example after successful training, the LiteRT Interpreter crashes:
14.11.2024 12:01:05 [ERROR   ] Error in process: tf_worker #1
14.11.2024 12:01:05 [ERROR   ] Traceback (most recent call last):
  File "/home/cam_ai/cam-ai/tf_workers/c_tfworkers.py", line 436, in runner
    self.process_buffer(schoolnr, self.logger, timeout)
  File "/home/cam_ai/cam-ai/tf_workers/c_tfworkers.py", line 618, in process_buffer
    self.models[schoolnr]['model'].invoke()
  File "/home/cam_ai/miniforge3/envs/tf/lib/python3.11/site-packages/tflite_runtime/interpreter.py", line 941, in invoke
    self._interpreter.Invoke()
RuntimeError: /tensorflow/tensorflow/lite/kernels/reduce.cc:510 reference_ops::QuantizedMeanOrSum( GetTensorData<integer_type>(input), input->params.zero_point, input->dims->data, input->dims->size, GetTensorData<integer_type>(output), data->multiplier, data->shift, output->params.zero_point, output->dims->data, output->dims->size, GetTensorData<int>(op_context.axis), num_axis, op_context.params->keep_dims, GetTensorData<int>(temp_index), GetTensorData<int>(resolved_axis), GetTensorData<int32_t>(temp_sum), false) was not true.Node number 34 (MEAN) failed to invoke.

**Comment by ludgerh** [comment]
Done with 1.8.2
